# Uncomment the next line to define a global platform for your project
  platform :ios, '14.0'

target 'Nest Thermostat Carbon Footprint Calculator (iOS)' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Nest Thermostat Carbon Footprint Calculator (iOS)
    pod 'GoogleSignIn'
end

target 'Nest Thermostat Carbon Footprint Calculator (macOS)' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Nest Thermostat Carbon Footprint Calculator (macOS)

end
